### ISSUE TITLE
フラッグに関して

### ISSUE THREAD

**Issue by ItoMasaki** [rionehome/rione_msgs#2]
現在レストランのUMLを見直しを行っている中で,
開始合図と終了合図をどのように行うかを検討中です.

案としては
- commandまたはcontent内に格納.
- 新たにflagを定義.

無駄な処理を行わなくて済むという点では後者を行うのが一番です.
現在の構造で進めていくなら前者が一番です.

設計的にはどちらにするのが一番でしょうか？

**Comment by yamatomatsuda** [comment]
新たにflagを定義して設計しましょう。
